-- 2023-12-19

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY
ORDER BY 1 ASC, 3 DESC