-- 코드를 입력하세요
-- SELECT DISTINCT CART_ID
-- FROM ()
-- ORDER BY 1

(SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt'
GROUP BY CART_ID)
intersect
(SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk'
GROUP BY CART_ID)
order by CART_ID