-- 2024.1.12
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY in ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY)
ORDER BY 2 DESC