-- 2024.1.12

SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, CAST(TO_CHAR(SALES_DATE, 'MM') AS INTEGER) AS MONTH, GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O
INNER JOIN USER_INFO U
ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER
ORDER BY 1, 2, 3 
