-- 2023.12.05

SELECT TO_CHAR(SALES_DATE , 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE TO_CHAR(SALES_DATE , 'MM') ='03'
UNION 
SELECT TO_CHAR(SALES_DATE , 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE , 'MM') ='03'
ORDER BY 1 ASC, 2 ASC, 3 ASC