-- 2023.12.06

SELECT R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I
INNER JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY 6 DESC, 4 DESC