WITH IS_RENTED AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-10-16' AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-10-16')

SELECT DISTINCT CAR_ID,
CASE WHEN CAR_ID IN (SELECT * FROM IS_RENTED) THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY 1 DESC

