select B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES* B.PRICE) AS TOTAL_SALES
from BOOK_SALES BS 
inner join BOOK B
on BS.BOOK_ID = B.BOOK_ID
inner join AUTHOR A
on B.AUTHOR_ID = A.AUTHOR_ID
where to_char(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
order by B.AUTHOR_ID, B.CATEGORY DESC