-- 코드를 입력하세요
SELECT tb.TITLE, tb.BOARD_ID, tr.REPLY_ID, tr.WRITER_ID, tr.CONTENTS, to_char(tr.CREATED_DATE, 'YYYY-MM-DD') as CREATED_DATE
from USED_GOODS_BOARD tb
inner join USED_GOODS_REPLY tr
on tb.BOARD_ID = tr.BOARD_ID
where to_char(tb.CREATED_DATE, 'YYYY-MM') = '2022-10'
order by tr.CREATED_DATE, tb.TITLE


-- SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d')
-- FROM USED_GOODS_BOARD AS B
-- INNER JOIN USED_GOODS_REPLY AS R ON B.BOARD_ID = R.BOARD_ID
-- WHERE B.CREATED_DATE LIKE '2022-10%'
-- ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;