-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
INNER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE ROUND((OUTS.DATETIME - INS.DATETIME),2) < 0
ORDER BY INS.DATETIME ASC
