-- 2023.12.20

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
INNER JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID 
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY CATEGORY 
ORDER BY 1 ASC 
